
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module de10_generic(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// Arduino //////////
	output 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
assign ARDUINO_IO[11] = 0;
assign ARDUINO_IO[3] = 0;


stoplight_moore_mac stoplight(.clk(~KEY[0]),.sensor(SW[1]),.reset(SW[9]),.HWY_color(ARDUINO_IO[10:8]),.FARM_color(ARDUINO_IO[2:0]));

//=======================================================
//  Structural coding
//=======================================================



endmodule
