
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Lab3_nios2(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);

//=======================================================
//  REG/WIRE declarations
//=======================================================
	
	wire [6:0] sseg0_data;
	wire [6:0] sseg1_data;
	wire [6:0] sseg2_data;
	wire [6:0] sseg3_data;
	wire [6:0] sseg4_data;
	wire [6:0] sseg5_data;
	
	de1_sseg_decoder sseg0(.data_in(sseg0_data), .data_out(HEX0));
	de1_sseg_decoder sseg1(.data_in(sseg1_data), .data_out(HEX1));
	de1_sseg_decoder sseg2(.data_in(sseg2_data), .data_out(HEX2));
	de1_sseg_decoder sseg3(.data_in(sseg3_data), .data_out(HEX3));
	de1_sseg_decoder sseg4(.data_in(sseg4_data), .data_out(HEX4));
	de1_sseg_decoder sseg5(.data_in(sseg5_data), .data_out(HEX5));
	
	myfirstnios2 u0 (
		.buttons_export (KEY[1:0]), // buttons.export
		.clk_clk        (CLOCK_50),        //     clk.clk
		.leds_export    (LEDR),    //    leds.export
		.reset_reset_n  (1'b1),  //   reset.reset_n
		.sseg_export    (sseg0_data),    //    sseg.export
		.sseg1_export   (sseg1_data),   //   sseg1.export
		.sw_export      (SW),      //      sw.export
		.sseg2_export   (sseg2_data),   //   sseg2.export
		.sseg3_export   (sseg3_data),   //   sseg3.export
		.sseg4_export   (sseg4_data),   //   sseg4.export
		.sseg5_export   (sseg5_data)    //   sseg5.export
	);


//=======================================================
//  Structural coding
//=======================================================



endmodule
